# Generated by Django 4.0.5 on 2022-06-15 20:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_tipodocumento'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ciudad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_ciudad', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='TipoContrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_tipo_contrato', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Personas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_documento', models.CharField(max_length=20)),
                ('primer_nombre', models.CharField(max_length=70)),
                ('otros_nombres', models.CharField(blank=True, max_length=70, null=True)),
                ('primer_apellido', models.CharField(max_length=70)),
                ('otros_apellidos', models.CharField(blank=True, max_length=70, null=True)),
                ('correo_electronico', models.CharField(max_length=70)),
                ('telefono', models.CharField(max_length=50)),
                ('perfil', models.TextField(max_length=250)),
                ('foto_persona', models.ImageField(blank=True, null=True, upload_to='')),
                ('ciudad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.ciudad')),
                ('tipo_documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.tipodocumento')),
            ],
        ),
    ]
