# Generated by Django 4.0.5 on 2022-06-15 20:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_ciudad_tipocontrato_personas'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cargos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Plazas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_vacante', models.IntegerField(max_length=70)),
                ('salario', models.FloatField(blank=True, max_length=70, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=70, null=True)),
                ('cargo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.cargos')),
                ('ciudad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.ciudad')),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.tipocontrato')),
            ],
        ),
    ]
