# Generated by Django 4.0.5 on 2022-06-15 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_alter_plazas_cantidad_vacante'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personas',
            name='correo_electronico',
            field=models.EmailField(max_length=254),
        ),
    ]
