# Generated by Django 4.0.5 on 2022-06-16 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_alter_plazas_descripcion_alter_plazas_salario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postulados',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
