# Generated by Django 4.0.5 on 2022-06-17 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0009_alter_postulados_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personas',
            name='foto_persona',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
